services:
  postgres:
    image: postgres:15-alpine

    container_name: dam-postgres

    restart: always

    env_file:
      - .env

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

    volumes:
      - dam-postgres-data:/var/lib/postgresql/data

    networks:
      - dam-network

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7

    container_name: dam-mongo

    restart: always

    env_file:
      - .env

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}

    ports:
      - '27017:27017'

    volumes:
      - dam_mongo_data:/data/db

    networks:
      - dam-network

  auth-api:
    build:
      context: .
      dockerfile: Docker/authservice.Dockerfile

    env_file:
      - .env

    restart: always

    ports:
      - '8001:8001'

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - dam-network

  gateway-api:
    container_name: gateway-api

    build:
      context: .
      dockerfile: Docker/gateway.Dockerfile

    env_file:
      - .env

    restart: always

    depends_on:
      - auth-api

    ports:
      - '8000:8000'

    networks:
      - dam-network

  web:
    build:
      context: .
      dockerfile: Docker/web.Dockerfile
    container_name: dam-web
    ports:
      - '80:80' 
    depends_on:
      - gateway-api
    networks:
      - dam-network
    restart: always

volumes:
  dam-postgres-data:
    external: true
  dam_mongo_data:
    external: true
  web-build:

networks:
  dam-network:
    external: true
